package MealPlanner.GUI.FoodItems;

import MealPlanner.GUI.Components.ButtonPanel;
import MealPlanner.Main;
import MealPlanner.Models.FoodItem;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class FoodItemSelectDialog extends JDialog {
    public FoodItem selectedFoodItem;

    public JPanel contentPane;
    public JPanel topPane;
    public JPanel foodPane;
    public JLabel label;

    public FoodItemSelectDialog() {
        super(Main.mainFrame, "Meal Planner - Select Item", true);
        setResizable(false);

        $$$setupUI$$$();

        contentPane = new JPanel();
        contentPane.setLayout(new BoxLayout(contentPane, BoxLayout.Y_AXIS));
        contentPane.add(topPane);

        // TODO: make this a scroll pane and add a search bar?
        foodPane = new JPanel();
        foodPane.setLayout(new BoxLayout(foodPane, BoxLayout.Y_AXIS));
        contentPane.add(foodPane);

        JPanel actionPanel = new JPanel();
        actionPanel.setAlignmentX(0.0f);
        FlowLayout actionPanelLayout = new FlowLayout(FlowLayout.CENTER, 0, 10);
        actionPanel.setLayout(actionPanelLayout);
        contentPane.add(actionPanel);

        ButtonPanel newItemButtonPanel = new ButtonPanel("New Item", event -> {
            new FoodItemUpdateDialog(null);
            populate();
        });
        actionPanel.add(newItemButtonPanel.contentPane);

        ButtonPanel cancelButtonPanel = new ButtonPanel("Cancel", event -> {
            selectedFoodItem = null;
            dispose();
        });
        actionPanel.add(cancelButtonPanel.contentPane);

        setContentPane(contentPane);

        populate();
        setLocationRelativeTo(Main.mainFrame);

        setVisible(true);
    }

    public void populate() {
        foodPane.removeAll();

        FoodItem[] foodItems = new FoodItem().select();
        if (foodItems.length == 0) {
            label.setText("There are no items in the database.");
        } else {
            label.setText("Select item...");

            for (FoodItem foodItem : foodItems) {
                foodPane.add(new FoodItemSelectPanel(foodItem.toString(), event -> {
                    selectedFoodItem = foodItem;
                    dispose();
                }, event -> {
                    new FoodItemUpdateDialog(foodItem);
                    populate();
                }).contentPane);
            }
        }

        pack();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        topPane = new JPanel();
        topPane.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 10));
        topPane.setAlignmentX(0.0f);
        final JSeparator separator1 = new JSeparator();
        separator1.setPreferredSize(new Dimension(10, 0));
        topPane.add(separator1);
        label = new JLabel();
        Font labelFont = this.$$$getFont$$$(null, Font.BOLD, -1, label.getFont());
        if (labelFont != null) label.setFont(labelFont);
        label.setText("Label");
        topPane.add(label);
        final JSeparator separator2 = new JSeparator();
        separator2.setPreferredSize(new Dimension(10, 0));
        topPane.add(separator2);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return topPane;
    }

}
