package MealPlanner.GUI.Recipes;

import MealPlanner.GUI.Components.Panel;
import MealPlanner.Models.FoodItem;
import MealPlanner.Models.RecipeIngredient;

import javax.swing.*;
import java.awt.*;

public class RecipeIngredientPanel extends Panel {
    public RecipeIngredient recipeIngredient;

    public JPanel contentPane;
    public JLabel label;
    public JButton detailsButton;

    public RecipeIngredientPanel(RecipeIngredient recipeIngredient) {
        $$$setupUI$$$();

        this.recipeIngredient = recipeIngredient;
        FoodItem foodItem = recipeIngredient.getFoodItem();
        label.setText(foodItem.formatQuantity(recipeIngredient.quantity.intValue()));
        detailsButton.addActionListener(event -> foodItem.getDetails(label.getText(), recipeIngredient.quantity));

        updateSize(contentPane);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 5));
        contentPane.setAlignmentX(0.0f);
        final JSeparator separator1 = new JSeparator();
        separator1.setPreferredSize(new Dimension(40, 0));
        contentPane.add(separator1);
        label = new JLabel();
        label.setHorizontalAlignment(0);
        label.setHorizontalTextPosition(0);
        label.setText("Label");
        contentPane.add(label);
        final JSeparator separator2 = new JSeparator();
        separator2.setPreferredSize(new Dimension(10, 0));
        contentPane.add(separator2);
        detailsButton = new JButton();
        detailsButton.setText("Details");
        contentPane.add(detailsButton);
        final JSeparator separator3 = new JSeparator();
        separator3.setPreferredSize(new Dimension(10, 0));
        contentPane.add(separator3);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
