BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE meal_plan CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -0942 THEN RAISE; END IF;
END;/
CREATE TABLE meal_plan
(
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    week_start DATE NOT NULL
)/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE recipe CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -0942 THEN RAISE; END IF;
END;/
CREATE TABLE recipe
(
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) DEFAULT NULL
)/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE meal CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -0942 THEN RAISE; END IF;
END;/
CREATE TABLE meal
(
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        PRIMARY KEY,
    plan_id INT NOT NULL
        REFERENCES meal_plan (id)
            ON DELETE CASCADE,
    day INT NOT NULL
        CHECK (day >= 1 AND day <= 7),
    type VARCHAR(9) NOT NULL
        CHECK (type IN ('breakfast', 'lunch', 'dinner')),
    recipe_id INT NOT NULL
        REFERENCES recipe (id)
            ON DELETE CASCADE
)/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE recipe_instruction CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -0942 THEN RAISE; END IF;
END;/
CREATE TABLE recipe_instruction
(
    recipe_id INT NOT NULL
        REFERENCES recipe (id)
            ON DELETE CASCADE,
    step INT NOT NULL,
    instruction VARCHAR(255) NOT NULL,
    PRIMARY KEY (recipe_id, step)
)/
CREATE INDEX recipe_instruction_recipe_id_idx ON recipe_instruction (recipe_id)/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE food_item CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -0942 THEN RAISE; END IF;
END;/
CREATE TABLE food_item
(
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    food_group VARCHAR(9) DEFAULT NULL
        CHECK (food_group IN ('fruit', 'vegetable', 'grains', 'protein', 'dairy')),
    unit VARCHAR(255) NOT NULL,
    calories INT DEFAULT NULL,
    fat INT DEFAULT NULL, -- all nutrition facts are store in milligrams (1g = 1000mg)
    cholesterol INT DEFAULT NULL,
    sodium INT DEFAULT NULL,
    carbohydrates INT DEFAULT NULL,
    dietary_fiber INT DEFAULT NULL,
    sugars INT DEFAULT NULL,
    protein INT DEFAULT NULL
)/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE recipe_ingredient CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -0942 THEN RAISE; END IF;
END;/
CREATE TABLE recipe_ingredient
(
    recipe_id INT NOT NULL
        REFERENCES recipe (id)
            ON DELETE CASCADE,
    food_id INT NOT NULL
        REFERENCES food_item (id)
            ON DELETE CASCADE,
    quantity INT NOT NULL,
    PRIMARY KEY (recipe_id, food_id)
)/
CREATE INDEX recipe_ingredient_recipe_id_idx ON recipe_ingredient (recipe_id)/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE fridge_item CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -0942 THEN RAISE; END IF;
END;/
CREATE TABLE fridge_item
(
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        PRIMARY KEY,
    food_id INT NOT NULL
        REFERENCES food_item (id)
            ON DELETE CASCADE,
    quantity INT NOT NULL
)/

INSERT INTO meal_plan
VALUES (DEFAULT, 'Week 15', DATE '2025-05-04')/

INSERT INTO recipe
VALUES (DEFAULT, 'Peanut Butter and Jelly Sandwich', 'Main Dish')/

INSERT INTO food_item
VALUES (DEFAULT, 'White Sandwich Bread', 'grains', 'slice', 77, 1000, NULL, 142, 14000, 800, 1600, 2600)/
INSERT INTO recipe_ingredient
VALUES (1, 1, 2)/
INSERT INTO fridge_item
VALUES (DEFAULT, 1, 26)/

INSERT INTO food_item
VALUES (DEFAULT, 'Peanut Butter', 'protein', 'tablespoon', 94, 8000, NULL, 76, 3900, 900, 1100, 3500)/
INSERT INTO recipe_ingredient
VALUES (1, 2, 2)/

INSERT INTO food_item
VALUES (DEFAULT, 'Grape Jelly', 'fruit', 'teaspoon', 19, NULL, NULL, 2, 500, 67, 367, NULL)/
INSERT INTO recipe_ingredient
VALUES (1, 3, 2)/

INSERT INTO recipe_instruction
VALUES (1, 1, 'Spread the peanut butter on one side of a slice of bread.')/
INSERT INTO recipe_instruction
VALUES (1, 2, 'Spread the grape jelly on one side of the other slice of bread.')/
INSERT INTO recipe_instruction
VALUES (1, 3, 'Put the two slices of bread together to form a sandwich.')/

INSERT INTO meal
VALUES (DEFAULT, 1, 1, 'lunch', 1)/

INSERT INTO recipe
VALUES (DEFAULT, 'Cheeseburger', 'Main Dish')/

INSERT INTO food_item
VALUES (DEFAULT, 'Hamburger Bun', 'grains', 'roll', 128, 1700, NULL, 230, 23000, 100, 2900, 4500)/
INSERT INTO recipe_ingredient
VALUES (2, 4, 2)/

INSERT INTO food_item
VALUES (DEFAULT, 'Beef', 'protein', 'ounce', 308, 20000, 101, 103, NULL, NULL, NULL, 31000)/
INSERT INTO recipe_ingredient
VALUES (2, 5, 4)/
INSERT INTO fridge_item
VALUES (DEFAULT, 5, 12)/

INSERT INTO food_item
VALUES (DEFAULT, 'Lettuce', 'vegetable', 'leaf', 16, 300, NULL, 7, 310, 2000, 1100, 1200)/
INSERT INTO recipe_ingredient
VALUES (2, 6, 2)/

INSERT INTO food_item
VALUES (DEFAULT, 'Cheese', 'dairy', 'slice', 113, 9300, 28, 183, 900, NULL, 100, 6400)/
INSERT INTO recipe_ingredient
VALUES (2, 7, 1)/

INSERT INTO recipe_instruction
VALUES (2, 1, 'Mold beef into shape of patty.')/
INSERT INTO recipe_instruction
VALUES (2, 2, 'Cook beef over oven for 25 minutes at 350 degrees.')/
INSERT INTO recipe_instruction
VALUES (2, 3, 'Put beef between two buns.')/
INSERT INTO recipe_instruction
VALUES (2, 4, 'Add cheese and lettuce on top.')/

INSERT INTO meal
VALUES (DEFAULT, 1, 2, 'breakfast', 1)/
INSERT INTO meal
VALUES (DEFAULT, 1, 2, 'dinner', 2)/