BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE meal_plan CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -0942 THEN RAISE; END IF;
END;/
CREATE TABLE meal_plan
(
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    week_start DATE NOT NULL
)/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE recipe CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -0942 THEN RAISE; END IF;
END;/
CREATE TABLE recipe
(
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) DEFAULT NULL
)/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE meal CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -0942 THEN RAISE; END IF;
END;/
CREATE TABLE meal
(
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        PRIMARY KEY,
    plan_id INT NOT NULL
        REFERENCES meal_plan (id)
            ON DELETE CASCADE,
    day INT NOT NULL
        CHECK (day >= 1 AND day <= 7),
    type VARCHAR(9) NOT NULL
        CHECK (type IN ('breakfast', 'lunch', 'dinner')),
    recipe_id INT NOT NULL
        REFERENCES recipe (id)
            ON DELETE CASCADE
)/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE recipe_instruction CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -0942 THEN RAISE; END IF;
END;/
CREATE TABLE recipe_instruction
(
    recipe_id INT NOT NULL
        REFERENCES recipe (id)
            ON DELETE CASCADE,
    step INT NOT NULL,
    instruction VARCHAR(255) NOT NULL,
    PRIMARY KEY (recipe_id, step)
)/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE food_item CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -0942 THEN RAISE; END IF;
END;/
CREATE TABLE food_item
(
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    food_group VARCHAR(9) DEFAULT NULL
        CHECK (food_group IN ('fruit', 'vegetable', 'grains', 'protein', 'dairy')),
    unit VARCHAR(255) NOT NULL,
    calories INT DEFAULT NULL,
    fat INT DEFAULT NULL, -- all nutrition facts are store in milligrams (1g = 1000mg)
    cholesterol INT DEFAULT NULL,
    sodium INT DEFAULT NULL,
    carbohydrates INT DEFAULT NULL,
    dietary_fiber INT DEFAULT NULL,
    sugars INT DEFAULT NULL,
    protein INT DEFAULT NULL
)/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE recipe_ingredient CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -0942 THEN RAISE; END IF;
END;/
CREATE TABLE recipe_ingredient
(
    recipe_id INT NOT NULL
        REFERENCES recipe (id)
            ON DELETE CASCADE,
    food_id INT NOT NULL
        REFERENCES food_item (id)
            ON DELETE CASCADE,
    quantity INT NOT NULL,
    PRIMARY KEY (recipe_id, food_id)
)/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE fridge_item CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -0942 THEN RAISE; END IF;
END;/
CREATE TABLE fridge_item
(
    id INT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    food_id INT
        REFERENCES food_item (id)
            ON DELETE CASCADE,
    quantity INT
)/

INSERT INTO meal_plan
VALUES (1, 'Week 15', DATE '2025-05-04')/

INSERT INTO recipe
VALUES (1, 'Peanut Butter and Jelly Sandwich', 'Main Dish')/

INSERT INTO food_item
VALUES (1, 'White Sandwich Bread', 'grains', 'slice', 77, 1000, NULL, 142, 14000, 800, 1600, 2600)/
INSERT INTO recipe_ingredient
VALUES (1, 1, 2)/
INSERT INTO fridge_item
VALUES (1, 1, 26)/

INSERT INTO food_item
VALUES (2, 'Peanut Butter', 'protein', 'tablespoon', 94, 8000, NULL, 76, 3900, 900, 1100, 3500)/
INSERT INTO recipe_ingredient
VALUES (1, 2, 2)/

INSERT INTO food_item
VALUES (3, 'Grape Jelly', 'fruit', 'teaspoon', 19, NULL, NULL, 2, 500, 67, 367, NULL)/
INSERT INTO recipe_ingredient
VALUES (1, 3, 2)/

INSERT INTO recipe_instruction
VALUES (1, 1, 'Spread the peanut butter on one side of a slice of bread.')/
INSERT INTO recipe_instruction
VALUES (1, 2, 'Spread the grape jelly on one side of the other slice of bread.')/
INSERT INTO recipe_instruction
VALUES (1, 3, 'Put the two slices of bread together, with the sides containing peanut butter and grape jelly facing one another, to form a sandwich.')/

INSERT INTO meal
VALUES (1, 1, 1, 'lunch', 1)/