BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE meal_plan CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -0942 THEN RAISE; END IF;
END;
/
CREATE TABLE meal_plan
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL
        PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    week_start DATE NOT NULL
)
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE recipe CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -0942 THEN RAISE; END IF;
END;
/
CREATE TABLE recipe
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL
        PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) DEFAULT NULL
)
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE meal CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -0942 THEN RAISE; END IF;
END;
/
CREATE TABLE meal
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL
        PRIMARY KEY,
    plan_id NUMBER NOT NULL
        REFERENCES meal_plan (id)
            ON DELETE CASCADE,
    day NUMBER NOT NULL
        CHECK (day >= 1 AND day <= 7),
    type VARCHAR(9) NOT NULL
        CHECK (type IN ('breakfast', 'lunch', 'dinner')),
    recipe_id NUMBER NOT NULL
        REFERENCES recipe (id)
            ON DELETE CASCADE
)
/
CREATE INDEX meal_plan_id_idx ON meal (plan_id)
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE recipe_instruction CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -0942 THEN RAISE; END IF;
END;
/
CREATE TABLE recipe_instruction
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL
        PRIMARY KEY,
    recipe_id NUMBER NOT NULL
        REFERENCES recipe (id)
            ON DELETE CASCADE,
    step NUMBER NOT NULL,
    instruction VARCHAR(255) NOT NULL
)
/
CREATE INDEX recipe_instruction_recipe_id_idx ON recipe_instruction (recipe_id)
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE food_item CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -0942 THEN RAISE; END IF;
END;
/
CREATE TABLE food_item
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL
        PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    food_group VARCHAR(9) DEFAULT NULL
        CHECK (food_group IN ('fruit', 'vegetable', 'grains', 'protein', 'dairy')),
    unit VARCHAR(255) NOT NULL,
    calories NUMBER DEFAULT NULL,
    fat NUMBER DEFAULT NULL, -- all nutrition facts are store in milligrams (1g = 1000mg)
    cholesterol NUMBER DEFAULT NULL,
    sodium NUMBER DEFAULT NULL,
    carbohydrates NUMBER DEFAULT NULL,
    dietary_fiber NUMBER DEFAULT NULL,
    sugars NUMBER DEFAULT NULL,
    protein NUMBER DEFAULT NULL
)
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE recipe_ingredient CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -0942 THEN RAISE; END IF;
END;
/
CREATE TABLE recipe_ingredient
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL
        PRIMARY KEY,
    recipe_id NUMBER NOT NULL
        REFERENCES recipe (id)
            ON DELETE CASCADE,
    food_id NUMBER NOT NULL
        REFERENCES food_item (id)
            ON DELETE CASCADE,
    quantity NUMBER(38, 3) NOT NULL
)
/
CREATE INDEX recipe_ingredient_recipe_id_idx ON recipe_ingredient (recipe_id)
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE fridge_item CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -0942 THEN RAISE; END IF;
END;
/
CREATE TABLE fridge_item
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL
        PRIMARY KEY,
    food_id NUMBER NOT NULL
        REFERENCES food_item (id)
            ON DELETE CASCADE,
    quantity NUMBER(38, 3) NOT NULL
)
/

CREATE OR REPLACE VIEW shopping_list_item AS
WITH recipe_needs AS (SELECT fi.id                    AS food_id,
                             NVL(SUM(ri.quantity), 0) AS needed_quantity
FROM food_item fi
         LEFT JOIN recipe_ingredient ri ON fi.id = ri.food_id
         LEFT JOIN meal m ON ri.recipe_id = m.recipe_id
         LEFT JOIN meal_plan mp ON m.plan_id = mp.id
WHERE mp.week_start >= CURRENT_DATE - 1
GROUP BY fi.id),
     fridge_stock AS (SELECT food_id,
                             NVL(SUM(quantity), 0) AS available_quantity
     FROM fridge_item
     GROUP BY food_id)
SELECT rn.food_id,
       GREATEST(rn.needed_quantity - NVL(fs.available_quantity, 0), 0) AS quantity
FROM recipe_needs rn
         LEFT JOIN fridge_stock fs ON rn.food_id = fs.food_id
WHERE GREATEST(rn.needed_quantity - NVL(fs.available_quantity, 0), 0) > 0
/

INSERT INTO meal_plan
VALUES (DEFAULT, 'Finals Week', DATE '2025-05-11')
/

INSERT INTO recipe
VALUES (DEFAULT, 'Peanut Butter and Jelly Sandwich', 'Main Dish')
/

INSERT INTO food_item
VALUES (DEFAULT, 'White Sandwich Bread', 'grains', 'slice', 77, 1000, NULL, 142, 14000, 800, 1600, 2600)
/
INSERT INTO recipe_ingredient
VALUES (DEFAULT, 1, 1, 2)
/
INSERT INTO fridge_item
VALUES (DEFAULT, 1, 26)
/

INSERT INTO food_item
VALUES (DEFAULT, 'Peanut Butter', 'protein', 'tablespoon', 94, 8000, NULL, 76, 3900, 900, 1100, 3500)
/
INSERT INTO recipe_ingredient
VALUES (DEFAULT, 1, 2, 2)
/

INSERT INTO food_item
VALUES (DEFAULT, 'Grape Jelly', 'fruit', 'teaspoon', 19, NULL, NULL, 2, 500, 67, 367, NULL)
/
INSERT INTO recipe_ingredient
VALUES (DEFAULT, 1, 3, 2)
/

INSERT INTO recipe_instruction
VALUES (DEFAULT, 1, 1, 'Spread the peanut butter on one side of a slice of bread.')
/
INSERT INTO recipe_instruction
VALUES (DEFAULT, 1, 2, 'Spread the grape jelly on one side of the other slice of bread.')
/
INSERT INTO recipe_instruction
VALUES (DEFAULT, 1, 3, 'Put the two slices of bread together to form a sandwich.')
/

INSERT INTO meal
VALUES (DEFAULT, 1, 1, 'lunch', 1)
/

INSERT INTO recipe
VALUES (DEFAULT, 'Cheeseburger', 'Main Dish')
/

INSERT INTO food_item
VALUES (DEFAULT, 'Hamburger Bun', 'grains', 'roll', 128, 1700, NULL, 230, 23000, 100, 2900, 4500)
/
INSERT INTO recipe_ingredient
VALUES (DEFAULT, 2, 4, 2)
/

INSERT INTO food_item
VALUES (DEFAULT, 'Beef', 'protein', 'ounce', 308, 20000, 101, 103, NULL, NULL, NULL, 31000)
/
INSERT INTO recipe_ingredient
VALUES (DEFAULT, 2, 5, 4)
/
INSERT INTO fridge_item
VALUES (DEFAULT, 5, 12)
/

INSERT INTO food_item
VALUES (DEFAULT, 'Lettuce', 'vegetable', 'leaf', 16, 300, NULL, 7, 310, 2000, 1100, 1200)
/
INSERT INTO recipe_ingredient
VALUES (DEFAULT, 2, 6, 2)
/

INSERT INTO food_item
VALUES (DEFAULT, 'Cheese', 'dairy', 'slice', 113, 9300, 28, 183, 900, NULL, 100, 6400)
/
INSERT INTO recipe_ingredient
VALUES (DEFAULT, 2, 7, 1)
/

INSERT INTO recipe_instruction
VALUES (DEFAULT, 2, 1, 'Mold beef into shape of patty.')
/
INSERT INTO recipe_instruction
VALUES (DEFAULT, 2, 2, 'Cook beef over oven for 25 minutes at 350 degrees.')
/
INSERT INTO recipe_instruction
VALUES (DEFAULT, 2, 3, 'Put beef between two buns.')
/
INSERT INTO recipe_instruction
VALUES (DEFAULT, 2, 4, 'Add cheese and lettuce on top.')
/

INSERT INTO meal
VALUES (DEFAULT, 1, 2, 'breakfast', 1)
/
INSERT INTO meal
VALUES (DEFAULT, 1, 2, 'dinner', 2)
/

INSERT INTO meal_plan
VALUES (DEFAULT, 'Week After Finals', DATE '2025-05-18')
/