package MealPlanner.Forms;

import MealPlanner.Models.FoodItem;
import MealPlanner.Models.FridgeItem;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class FridgeItemPanel extends Panel {
    public FridgeItem fridgeItem;

    public JPanel contentPane;
    public JLabel label;
    public JButton editButton;
    public JButton detailsButton;

    public FridgeItemPanel(FridgeItem fridgeItem) {
        $$$setupUI$$$();

        this.fridgeItem = fridgeItem;
        FoodItem foodItem = fridgeItem.getFoodItem();
        label.setText("%s %s(s) of %s".formatted(fridgeItem.quantity, foodItem.unit, foodItem.name));
        detailsButton.addActionListener(event -> {
            // TODO
        });
        editButton.addActionListener(event -> {
            // TODO
        });

        updateSize(contentPane);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 5));
        contentPane.setAlignmentX(0.0f);
        final JSeparator separator1 = new JSeparator();
        separator1.setPreferredSize(new Dimension(10, 0));
        contentPane.add(separator1);
        label = new JLabel();
        Font labelFont = this.$$$getFont$$$(null, -1, -1, label.getFont());
        if (labelFont != null) label.setFont(labelFont);
        label.setHorizontalAlignment(0);
        label.setHorizontalTextPosition(0);
        label.setText("Label");
        contentPane.add(label);
        final JSeparator separator2 = new JSeparator();
        separator2.setPreferredSize(new Dimension(10, 0));
        contentPane.add(separator2);
        detailsButton = new JButton();
        detailsButton.setText("Details");
        contentPane.add(detailsButton);
        final JSeparator separator3 = new JSeparator();
        separator3.setPreferredSize(new Dimension(10, 0));
        contentPane.add(separator3);
        editButton = new JButton();
        editButton.setText("Edit");
        contentPane.add(editButton);
        final JSeparator separator4 = new JSeparator();
        separator4.setPreferredSize(new Dimension(10, 0));
        contentPane.add(separator4);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
