package MealPlanner.Forms;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class InputPanel extends Panel {
    public JPanel contentPane;
    public JLabel keyLabel;
    public JTextField inputField;

    public InputPanel(String key, String value, int columns) {
        $$$setupUI$$$();

        keyLabel.setText(key);
        inputField.setText(value);
        inputField.setColumns(columns);

        updateSize(contentPane);
    }

    public InputPanel(String key, String value, int columns, boolean enabled) {
        this(key, value, columns);

        inputField.setEnabled(enabled);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 2));
        contentPane.setAlignmentX(0.0f);
        final JSeparator separator1 = new JSeparator();
        separator1.setPreferredSize(new Dimension(10, 0));
        contentPane.add(separator1);
        keyLabel = new JLabel();
        Font keyLabelFont = this.$$$getFont$$$(null, -1, -1, keyLabel.getFont());
        if (keyLabelFont != null) keyLabel.setFont(keyLabelFont);
        keyLabel.setText("Label");
        contentPane.add(keyLabel);
        final JSeparator separator2 = new JSeparator();
        separator2.setPreferredSize(new Dimension(20, 0));
        contentPane.add(separator2);
        inputField = new JTextField();
        inputField.setColumns(30);
        contentPane.add(inputField);
        final JSeparator separator3 = new JSeparator();
        separator3.setPreferredSize(new Dimension(10, 0));
        contentPane.add(separator3);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
