package MealPlanner.Forms;

import MealPlanner.Main;
import MealPlanner.Models.Meal;
import MealPlanner.Models.MealPlan;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.sql.Date;
import java.util.Locale;

public class MealPlanPanel extends Panel {
    public MealPlan mealPlan;

    public JPanel contentPane;
    public JPanel topPane;
    public JLabel weekLabel;
    public JLabel nameLabel;
    public JButton editButton;

    public MealPlanPanel(MealPlan mealPlan) {
        $$$setupUI$$$();

        contentPane = new JPanel();
        contentPane.setLayout(new BoxLayout(contentPane, BoxLayout.Y_AXIS));
        contentPane.add(topPane);

        this.mealPlan = mealPlan;
        Date weekEnd = mealPlan.getWeekEnd();
        weekLabel.setText("%s to %s".formatted(mealPlan.week_start, weekEnd));
        nameLabel.setText(mealPlan.name);
        editButton.addActionListener(event -> {
            new MealPlanUpdateFrame(mealPlan);
            Main.mainFrame.populateMealPlansTab();
        });

        for (Meal meal : mealPlan.getMeals()) {
            contentPane.add(new MealPanel(mealPlan, meal).contentPane);
        }

        JSeparator separator = new JSeparator();
        separator.setMaximumSize(new Dimension(Integer.MAX_VALUE, 2));
        contentPane.add(separator);

        updateSize(topPane);
        updateSize(contentPane);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        topPane = new JPanel();
        topPane.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 5));
        topPane.setAlignmentX(0.0f);
        final JSeparator separator1 = new JSeparator();
        separator1.setPreferredSize(new Dimension(10, 0));
        topPane.add(separator1);
        weekLabel = new JLabel();
        Font weekLabelFont = this.$$$getFont$$$(null, Font.ITALIC, -1, weekLabel.getFont());
        if (weekLabelFont != null) weekLabel.setFont(weekLabelFont);
        weekLabel.setText("Label");
        topPane.add(weekLabel);
        final JSeparator separator2 = new JSeparator();
        separator2.setPreferredSize(new Dimension(20, 0));
        topPane.add(separator2);
        nameLabel = new JLabel();
        Font nameLabelFont = this.$$$getFont$$$(null, Font.BOLD, -1, nameLabel.getFont());
        if (nameLabelFont != null) nameLabel.setFont(nameLabelFont);
        nameLabel.setHorizontalAlignment(0);
        nameLabel.setHorizontalTextPosition(0);
        nameLabel.setText("Label");
        topPane.add(nameLabel);
        final JSeparator separator3 = new JSeparator();
        separator3.setPreferredSize(new Dimension(20, 0));
        topPane.add(separator3);
        editButton = new JButton();
        editButton.setText("Edit");
        topPane.add(editButton);
        final JSeparator separator4 = new JSeparator();
        separator4.setPreferredSize(new Dimension(10, 0));
        topPane.add(separator4);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return topPane;
    }

}
