package MealPlanner.Forms;

import javax.swing.*;
import java.awt.*;

public class RecipeIngredientPanel {
    public JPanel contentPane;
    public JLabel stepLabel;
    public JLabel label;

    public RecipeIngredientPanel() {
        $$$setupUI$$$();
    }

    public void updateSize() {
        Dimension preferredSize = contentPane.getPreferredSize();
        contentPane.setMaximumSize(new Dimension(preferredSize.width, preferredSize.height));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new FlowLayout(FlowLayout.LEFT, 40, 5));
        contentPane.setAlignmentX(0.0f);
        label = new JLabel();
        label.setHorizontalAlignment(0);
        label.setHorizontalTextPosition(0);
        label.setText("Label");
        contentPane.add(label);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
