package MealPlanner.GUI.Components;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

public class ButtonPanel extends Panel {
    public JPanel contentPane;
    public JButton button;
    public JSeparator leftSeparator;
    public JSeparator rightSeparator;

    public ButtonPanel(String text, ActionListener onClick) {
        $$$setupUI$$$();

        button.setText(text);
        button.addActionListener(onClick);

        updateSize(contentPane);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 5));
        contentPane.setAlignmentX(0.0f);
        leftSeparator = new JSeparator();
        leftSeparator.setPreferredSize(new Dimension(10, 0));
        contentPane.add(leftSeparator);
        button = new JButton();
        button.setText("Button");
        contentPane.add(button);
        rightSeparator = new JSeparator();
        rightSeparator.setPreferredSize(new Dimension(10, 0));
        contentPane.add(rightSeparator);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
